# Generated by Django 2.2.6 on 2019-10-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191023_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
